version: '3.8'

volumes:
  pgdata:
  static:
  media:

services:
  redis:
    image: redis
    expose:
      - "6379"
  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "python manage.py collectstatic &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media
  celery:
    build: .
    tty: true
    restart: always
    command: celery -A config worker -l INFO
    env_file:
      - .env
    volumes:
      - ./:/app
      - media:/app/media