version: '3.8'

services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL",  "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      retries: 3
      timeout: 5s
  redis:
    image: redis
    expose:
      - "6379"
  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    restart: on-failure
    depends_on:
      - redis
      - app
    env_file:
      - .env
    volumes:
      - media:/app/media
volumes:
  pg_data:
  static:
  media:
